[tool.poetry]
name = "f1_analytics_env"
version = "0.0.1"
description = "Analyze F1 Data"
authors = ["Davide Casolari"]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = ">=3.8,<3.9.7 || >3.9.7"
streamlit = "1.32.0"
fastf1 = "^3.3.1"
